version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.17.5
  - dependency-name: gatsby-link
    versions:
    - 1.6.46
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 2.0.11
